---
title: Triggerise
timezone: UTC
collections:
  anbi-status:
    title: ANBI Status
    output: true
  annual-reports:
    title: Annual Reports
    output: true
  financial-reports:
    title: Financial Reports
    output: true
  posts:
    title: Posts
    output: true
  privacy-policy:
    title: Privacy Policies
    output: true
  social-icons:
    title: Social Icons
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: annual-reports
  values:
    label: Annual Report
    filter: AnnualReport
- scope:
    path: ''
    type: financial-reports
  values:
    label: Financial Report
    filter: FinancialReport
- scope:
    path: ''
    type: anbi-status
  values:
    label: ANBI Publication
    filter: ANBIStatus
permalink: pretty
