---
title: Triggerise
timezone: UTC
collections:
  annual-reports:
    title: Annual Reports
    output: true
  financial-reports:
    title: Financial Reports
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: annual-reports
  values:
    label: Annual Report
    filter: AnnualReport
- scope:
    path: ''
    type: financial-reports
  values:
    label: Financial Report
    filter: FinancialReport
permalink: pretty
