apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Release.Name}}"
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  minReadySeconds: 30
  selector:
    matchLabels:
      {{- include "labels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxUnavailable: "0%"
        maxSurge: "50%"
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
      annotations:
        scrappable: "true"
    spec:
      serviceAccountName: "{{.Release.Name}}"
      containers:
        - name: main
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{.Values.image.pullPolicy}}"
          resources:
            limits:
              cpu: {{.Values.resources.limits.cpu | quote}}
              memory: {{.Values.resources.limits.memory | quote}}
            requests:
              cpu: {{.Values.resources.requests.cpu | quote}}
              memory: {{.Values.resources.requests.memory | quote}}
          ports:
            - containerPort:  {{.Values.service.internalPort}}
              name: http
          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: vhost.conf
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 20 && /usr/sbin/nginx -s quit"]
          {{- if $.Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 15
          {{- end }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nginx-config
        configMap:
          name: {{ .Release.Name }}-nginx-config
