{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Release.Name }}
  labels:
    {{- include "labels" . | nindent 4 }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  tls:
    {{- range .Values.ingress.hosts }}
    - hosts:
      - {{ .name | quote }}
      secretName: {{ .secret | quote }}
    {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .name | quote }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ $.Release.Name }}
                port:
                  number: {{ $.Values.service.externalPort }}
    {{- end }}
{{- end }}

