apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;

    load_module modules/ngx_http_js_module.so;

    events {
      worker_connections  20000;
    }

    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
      log_format custom_log '$http_x_forwarded_for - $remote_user [$time_local] $host "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time $upstream_response_time $pipe';
      sendfile on;
      keepalive_timeout 65;
      # Tell Nginx not to send out partial frames; this increases throughput
      # since TCP frames are filled up before being sent out. (adds TCP_CORK)
      tcp_nopush on;
      include /etc/nginx/conf.d/*.conf;
    }

  vhost.conf: |
    map $request_uri $loggable {
      ~/_health/lb 0;
      ~/css.* 0;
      ~/js.* 0;
      /favicon.ico 0;
      default 1;
    }

    server {
      listen       80;
      server_name  localhost;
      root /usr/share/nginx/html;

      error_log  /dev/stderr;
      access_log /dev/stdout custom_log if=$loggable;
      location / {
        add_header 'Access-Control-Allow-Origin' '*'; add_header 'X-Robots-Tag' 'none';
        add_header 'X-Frame-Options' 'sameorigin';

        index  index.html;
        try_files $uri /index.html;
      }

      error_page   500 502 503 504  /50x.html;

      location = /50x.html {
        root   /usr/share/nginx/html;
      }

      location /_health/lb {
        return 200;
      }
    }
