apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name | quote }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  ports:
    - port: {{.Values.service.externalPort}}
      targetPort: {{.Values.service.internalPort}}
  selector:
    app: {{.Release.Name | quote }}
  type: {{ default "ClusterIP" .Values.service.type | quote }}
