apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{.Release.Name}}"
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-10"
