apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{.Release.Name}}
  namespace: workflows
spec:
  template:
    serviceAccountName: workflow
  dependencies:
    - name: github
      eventSourceName: github
      eventName: triggerise
      filters:
        exprLogicalOperator: "or"
        exprs:
          - expr: "event_type == 'push' && repository == 'triggerise.github.io' && pusher != 'tiko-dude'"
            fields:
              - name: event_type
                path: body.X-GitHub-Event
              - name: repository
                path: body.repository.name
              - name: pusher
                path: body.pusher.name
        data:
          - path: body.ref
            type: string
            value:
              - 'refs/heads/develop'
  triggers:
    - template:
        name: "{{.Release.Name}}-workflow"
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: "triggerise-org-workflow-"
                namespace: workflows
                labels:
                  branch:
                  sha:
              spec:
                workflowMetadata:
                  labels:
                    workflows.argoproj.io/container-runtime-executor: emissary
                archiveLogs: true
                serviceAccountName: workflow
                volumes:
                - name: dockerconfig
                  configMap:
                    name: dockerconfig
                - name: idrsa
                  secret:
                    secretName: workflow-ssh
                    defaultMode: 0600
                    items:
                    - key: id_rsa
                      path: id_rsa
                arguments:
                  parameters:
                  - name: revision
                  - name: git_commit
                  - name: application
                    value: "triggerise.github.io"
                  - name: repository
                    value: "triggerise.github.io"
                  - name: image
                    value: "387002922338.dkr.ecr.eu-west-1.amazonaws.com/workflows/docker-dind:latest"
                ttlStrategy:
                  secondsAfterCompletion: 432000
                  secondsAfterSuccess: 432000
                  secondsAfterFailure: 432000
                podDisruptionBudget:
                  minAvailable: 100%
                entrypoint: main
                templates:
                - name: main
                  steps:

                  - - name: build-image
                      templateRef:
                        name: tiko-web-utils
                        template: build

                  - - name: patch-k8s-values
                      templateRef:
                        name: tiko-utils
                        template: patch-k8s-values

          parameters:
          - src:
              dependencyName: github
              dataTemplate: '{{ printf "{{trimPrefix \"refs/heads/\" .Input.body.ref}}" }}'
            dest: spec.arguments.parameters.0.value
          - src:
              dependencyName: github
              dataKey: body.after
            dest: spec.arguments.parameters.1.value
          - src:
              dependencyName: github
              dataTemplate: '{{ printf "{{.Input.body.ref | replace \"refs/heads/\" \"\" | replace \"/\" \"-\" }}" }}'
            dest: metadata.labels.branch
          - src:
              dependencyName: github
              dataTemplate: "{{ printf "{{.Input.body.after}}" }}"
            dest: metadata.labels.branch
            dest: metadata.labels.sha
