name: Slack Notify

on:
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author # selectable (default: repo,message)
          custom_payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "You have a new request:\n*<fakeLink.toEmployeeProfile.com|Fred Enriquez - New device request>*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Type:*\nComputer (laptop)"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*When:*\nSubmitted Aut 10"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Last Update:*\nMar 10, 2015 (3 years, 5 months)"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Reason:*\nAll vowel keys aren't working."
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Specs:*\n\"Cheetah Pro 15\" - Fast, really fast\""
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "Approve"
                      },
                      "style": "primary",
                      "value": "click_me_123"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "Deny"
                      },
                      "style": "danger",
                      "value": "click_me_123"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
        if: always()
